version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  BeforeInstall:
    - location: scripts/do_before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/do_after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/do_application_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/do_application_stop.sh
      timeout: 300
      runas: root
